### ISSUE TITLE
Add support for Teams chat and EduAssignments

### ISSUE THREAD

**Issue by HonbraDev** [sreeise/graph-rs-sdk#403]
I couldn't find them anywhere in the crate. Sorry if I'm just bad at looking.

**Comment by sreeise** [comment]
Hey, no worries. Thats what feature requests are for. 

Are you referring to [education assignments](https://learn.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0) such as this GET assignments:

`GET /education/classes/{id}/assignments/{id}`

If so, you right those are not in master or the latest crate version. The next release should be within a week at most and that is for #392 and that branch has the education assignments API included:

https://github.com/sreeise/graph-rs/blob/48754f644e2716bda58e606274fa894c234386f9/src/education/education_assignments/request.rs#L1-L176

There are a few breaking changes though so you would need to update your code. The changes are minimal though. Its mainly just using the async client as the default client so doing `Graph::new` is the async client. I am not planning on updating current master with any new APIs.

**Comment by sreeise** [comment]
@HonbraDev I didnt see the Teams chat part. Which API are you referring to? `/chats` path or is there a specific chats for teams that I am missing?

**Comment by sreeise** [comment]
> Thanks for the quick response. Yes, I was referring to 1:1 chats under the `/chats` path and I can see everything I needed in the branch you sent.

No problem and glad to help. 

> I'd also like to ask why is `graph-rs-types` archived? I'm okay with defining my own structs, just curious.

There was a few reasons I stopped supporting that repo, but ill provide a short list.

- It took a lot of time parsing those types because they are all in xml. Those types are written in OData Common Schema Definition Language. And 
-  I also wrote the parser for that repo in Python and the codgen was in python as well so I was writing Rust code using Python. Its not unusual to do codegen using another language but in this case it was just a lot of extra work. 
- The parser in this repo and the codegen is in Rust and its parsing OpenAPI JSON which is much easier to do. But that JSON doesnt have types in them.
- If those types get updated in the API and the code is not yet generated for those then the client breaks for any method that returns that type. And its happened to me a few times. There is no announcement or official release of the API getting updated. Well there might be but I don't have the time to pay attention to it enough to make sure those types are always right. 😆 
- The crate is much easier to maintain when each method doesnt require there to be a concrete type returned. It also just allows the user to get the body of the response in different formats such as bytes, streams, custom types, serde_json, etc. 

Heres an example of the starting XML:

```
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:DataServices>
    <Schema Namespace="microsoft.graph" Alias="graph" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EnumType Name="appliedConditionalAccessPolicyResult">
        <Member Name="success" Value="0" />
        <Member Name="failure" Value="1" />
        <Member Name="notApplied" Value="2" />
        <Member Name="notEnabled" Value="3" />
        <Member Name="unknown" Value="4" />
        <Member Name="unknownFutureValue" Value="5" />
      </EnumType>
      <EnumType Name="conditionalAccessStatus">
        <Member Name="success" Value="0" />
        <Member Name="failure" Value="1" />
        <Member Name="notApplied" Value="2" />
        <Member Name="unknownFutureValue" Value="3" />
      </EnumType>
      <EnumType Name="groupType">
        <Member Name="unifiedGroups" Value="0" />
        <Member Name="azureAD" Value="1" />
        <Member Name="unknownFutureValue" Value="2" />
      </EnumType>
```

That metadata comes from the [Graph API](https://learn.microsoft.com/en-us/graph/traverse-the-graph) as well:
`https://graph.microsoft.com/v1.0/$metadata` and `https://graph.microsoft.com/beta/$metadata`. In other languages, like Microsoft's own C# they have extensive tools and libraries to generate code using that metadata but this is not true in Rust and it is a ton of work to do for someone doing this during their free time. 

That was kind of a rant haha. Sorry about that.


> Edit: Oh and I forgot to mention, I'm just goofing around with the API and you can't break code when there is none yet so I'm gonna switch branches and tell you if something breaks for some reason.

Sure that would be great. Im still finishing up some things on the branch so I apoligize if I accidently push code that doesnt compile 😄
