### ISSUE TITLE
Allow custom type conversion on Streams

### ISSUE THREAD

**Issue by edfloreshz** [sreeise/graph-rs-sdk#442]
I'm developing an app that has a trait called `TaskService` which has a method `get_task_list_stream` that returns `Stream<Item = List>`, however, the only data type capable of correctly deserializing the response is `TodoTaskList`, such type need to be converted to `List` before creating the stream, but `.stream::<T>()` provides a way to convert to a single type.

Trying to convert to another type would require consuming the stream, which is not ideal.

Could this crate have a way to provide a closure that does custom conversion and returns `Result<T, ErrorMessage>`?

```rust
.custom_stream::<T>(|T| { ... })?
```

Then, the `http_response` method could call the closure and use the `Result`.

**Comment by sreeise** [comment]
> I'm developing an app that has a trait called `TaskService` which has a method `get_task_list_stream` that returns `Stream<Item = List>`, however, the only data type capable of correctly deserializing the response is `TodoTaskList`, such type need to be converted to `List` before creating the stream, but `.stream::<T>()` provides a way to convert to a single type.
> 
> Trying to convert to another type would require consuming the stream, which is not ideal.
> 
> Could this crate have a way to provide a closure that does custom conversion and returns `Result<T, ErrorMessage>`?
> 
> ```rust
> .custom_stream::<T>(|T| { ... })?
> ```
> 
> Then, the `http_response` method could call the closure and use the `Result`.

Hey @edfloreshz 

I am not exactly sure what your looking to do but i'd be willing to see if I can help or provide something but I just want to get some clarification on what that is.

Specifically, can you possibly provide an example of what this may look like or given some more details on what your wanting to do? When you say custom conversion are you referring to providing a closure that gets access to the underlying response or response body and does the custom conversion iteself?

**Comment by edfloreshz** [comment]
Hi, I managed to resolve the issue using a combination of streams and channels, I'm not entirely sure if this is the best approach, but let me explain myself better just for context.

The trait looks something like this:

```rust
pub trait TodoProvider {
  /// Returns a stream of tasks.
  fn get_tasks(&mut self, parent_list: String) -> Result<Stream<Task>>;
}
```

This is the request I'm making inside my trait implementation:

```rust
let mut stream = self
  .client
  .me()
  .todo()
  .list(parent_list.clone())
  .tasks()
  .list_tasks()
  .paging()
  .stream::<Collection<TodoTask>>()?;
```

One issue I'm facing is that I can't convert the body of the request into `TodoTask` directly, I have to pass in `Collection<TodoTask>` to the generic type of the `stream` method, such type looks something like this:

```rust
pub struct Collection<T> {
  pub value: Vec<T>,
}
```

Given that the Todo API returns a JSON similar to this:

```json
{
  "value": [ { }, { } ]
}
```
This is the only type capable of deserializing the response correctly, passing `TodoTask` results in an error.

Once the response is parsed correctly, the stream works, however, I now need to convert `TodoTask` into `Task` to comply with the trait, but to do that I'd have to consume the stream first, convert and then create a new stream from that.

I was looking for a way to handle the conversion myself during the stream creation by passing a closure into the `stream` method, however, my approach may not be the best.

Let me know your thoughts.

**Comment by sreeise** [comment]
> Hi, I managed to resolve the issue using a combination of streams and channels, I'm not entirely sure if this is the best approach, but let me explain myself better just for context.
> 
> The trait looks something like this:
> 
> ```rust
> pub trait TodoProvider {
>   /// Returns a stream of tasks.
>   fn get_tasks(&mut self, parent_list: String) -> Result<Stream<Task>>;
> }
> ```
> 
> This is the request I'm making inside my trait implementation:
> 
> ```rust
> let mut stream = self
>   .client
>   .me()
>   .todo()
>   .list(parent_list.clone())
>   .tasks()
>   .list_tasks()
>   .paging()
>   .stream::<Collection<TodoTask>>()?;
> ```
> 
> One issue I'm facing is that I can't convert the body of the request into `TodoTask` directly, I have to pass in `Collection<TodoTask>` to the generic type of the `stream` method, such type looks something like this:
> 
> ```rust
> pub struct Collection<T> {
>   pub value: Vec<T>,
> }
> ```
> 
> Given that the Todo API returns a JSON similar to this:
> 
> ```json
> {
>   "value": [ { }, { } ]
> }
> ```
> 
> This is the only type capable of deserializing the response correctly, passing `TodoTask` results in an error.
> 
> Once the response is parsed correctly, the stream works, however, I now need to convert `TodoTask` into `Task` to comply with the trait, but to do that I'd have to consume the stream first, convert and then create a new stream from that.
> 
> I was looking for a way to handle the conversion myself during the stream creation by passing a closure into the `stream` method, however, my approach may not be the best.
> 
> Let me know your thoughts.

Yeah I think I understand what your wanting and honestly this is probably a limitation of Streams and not something that can just be handled by providing the underlying body - which is still a stream at this point.

There are probably a couple of ways to get around this though. I think the easiest and most conveniant, and better than providing a way to do a closure, would be to make a conversion function that is provided to serde deserialize such as through a FromType annotation or a custom deserialize method. In this way you would achieve the exact same thing as if you were to have a closure to the type and better overall as you are not having to run a closure each time to convert the response body.

I did try to see what type of issues your running into by running my own simple calls to the tasks/lists API's and I basically did this:

```rust
use http::Response as HttpResponse;

async fn collect_tasks(client: &mut Graph, list_id: &str) {
    let stream = client.me()
        .todo()
        .list(list_id)
        .tasks()
        .list_tasks()
        .paging()
        .stream::<serde_json::Value>()
        .unwrap();

    let s2 = stream
        .filter_map(|resp| async move { map_result_to_task(resp) })
         // FlatMap only works on a List of Streams and currently this is either Vec<Vec<Task>>
         // or Stream<Vec<Vec<Taks>>> so wrap our tasks in a stream iter.
        .flat_map(|tasks_lists| stream::iter(tasks_lists))
        .collect::<Vec<Task>>();

    let value = s2.await;
    println!("{:#?}", value);
}

// The GraphResult<HttpResponse<Result<serde_json::Value, ErrorMessage>>> is the actual types
// you will find in the steam methods. Unfortuantely I forgot to export the public types called 
// PagingResult and PagingResponse. Gonna add this as a ticket.
fn map_result_to_task(task_result: GraphResult<HttpResponse<Result<serde_json::Value, ErrorMessage>>>) -> Option<Vec<Task>> {
    println!("{:#?}", task_result);
    match task_result {
        Ok(response) => map_to_task(response.into_body()),
        Err(_) => None,
    }
}

fn map_to_task(task: Result<Value, ErrorMessage>) -> Option<Vec<Task>> {
    let value = task.ok()?;
    // [Value] of Tasks
    let tasks: Vec<serde_json::Value> =  value["value"].as_array().cloned()?;

    // Vec<Task>
    let task_list = tasks.iter()
        .flat_map(|t| serde_json::from_value(t.clone()).ok())
        .collect::<Vec<Task>>();

    Some(task_list)
}

```

So you can see that even though I still have the original stream, I had to wrap the result of the filter_map, which is a stream itself, in a stream iterator because attempting to flatten a Vec<Vec<Task>> down to Vec<Task> only worked on a stream when it is stream iterator not a regular one.

Hope this helps. After looking at this I don't know that providing some type of method for a closure would make any difference to what your trying to do. But I admit im honestly not sure about any other ways to do what your trying to do besides custom serde conversions which in my experience are pretty easy to use if you want to go that route. Let me know if im getting it wrong as far as what your asking though or if you just want to discuss it further (I am not immune to being completely wrong that is for sure).

**Comment by edfloreshz** [comment]
Thanks for the response, I tried your approach and it worked like a charm 🎉 

My only concern is that we're consuming the first stream and creating a new one, isn't this going to cause a bottleneck for large data sets?

**Comment by sreeise** [comment]
> Thanks for the response, I tried your approach and it worked like a charm 🎉
> 
> My only concern is that we're consuming the first stream and creating a new one, isn't this going to cause a bottleneck for large data sets?

I mean yeah probably. Well honestly this whole thing could be a bottleneck to be honest. That example wasn't really meant to be _optimized_ for performance or anything. There are several simple things that can be cleaned up in that example regardless of the size of the data set such as converting to your own type first instead of `serde_json::Value` and obviously not cloning, let alone cloning twice like I did. 

So I guess really it depends on what your trying to acomplish. Do you need all of the data right now or can you process each one as its needed - which is a good use for streams. Once you optimize a simple solution how does that peform against large data sets is something that would probably have to be benchmarked and continual refactoring - that exaple yes almost certainly would be a performance problem so in large data sets because of several factors such as its blocking the main thread to do the work and not taking any extra steps to increase performance. Like I said, its an example I wrote in a few minutes so not meant to be performant.

I'm also not sure that it did consume the stream before creating the second one because we didn't` .await` the first stream. Curios as to what makes you think that it did? I believe It may have consumed it on call to `s2.await` but I don't know for sure. And I believe stream::iter is just creating an immediately Ready stream of values, as opposed to a future value. But im not 100% on the exact internal workings of streams either.

**Comment by sreeise** [comment]
You probably already know but there is also a ton of other StreamExt or [TryStreamExt](https://docs.rs/futures/latest/futures/stream/trait.TryStreamExt.html#) related things you could use. stream::iter was just the easiest and quickest to use for that example.

**Comment by edfloreshz** [comment]
Ah, I'm pretty new to streams so don't take my word for granted, it's my first time working with them and I still have some misconceptions.

I'll keep optimizing the code.

Feel free to close this👍🏼
