### ISSUE TITLE
InvalidData: stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by samvv** [sreeise/graph-rs-sdk#465]
**Describe the bug**

I _think_ this is a bug though I'm not entirely sure.

I get:

```
Custom {
    kind: InvalidData,
    error: "stream did not contain valid UTF-8",
}
```

**To Reproduce**

Taken from the examples:

```rust
let res = self
    .graph
    .drive(DRIVE_ID)
    .item_by_path(PATH_TO_DRIVE_ITEM)
    .update_items_content(BodyRead::from_async_read(reader).await?)
    .send()
```

`reader` is a variable that implements `tokio::io::AsyncRead` and may be used to read anything, not just Unicode.

**Expected behavior**

No error. A binary file should successfully upload.

**Desktop:**

 - SDK version: v2.0.0-beta.0
 - OS: Windows
 - Rust: rustc 1.77.0-nightly
 - Editor: VSCode

**Additional context**

Still working on the same file synchronization service. It's almost finished.

**Comment by sreeise** [comment]
> **Describe the bug**
> 
> I _think_ this is a bug though I'm not entirely sure.
> 
> I get:
> 
> ```
> Custom {
>     kind: InvalidData,
>     error: "stream did not contain valid UTF-8",
> }
> ```
> 
> **To Reproduce**
> 
> Taken from the examples:
> 
> ```rust
> let res = self
>     .graph
>     .drive(DRIVE_ID)
>     .item_by_path(PATH_TO_DRIVE_ITEM)
>     .update_items_content(BodyRead::from_async_read(reader).await?)
>     .send()
> ```
> 
> `reader` is a variable that implements `tokio::io::AsyncRead` and may be used to read anything, not just Unicode.
> 
> **Expected behavior**
> 
> No error. A binary file should successfully upload.
> 
> **Desktop:**
> 
>     * SDK version: v2.0.0-beta.0
> 
>     * OS: Windows
> 
>     * Rust: rustc 1.77.0-nightly
> 
>     * Editor: VSCode
> 
> 
> **Additional context**
> 
> Still working on the same file synchronization service. It's almost finished.

Im guessing this is because the `Content-Type` header is not set for either octet-stream or it may even work with text/plain.

Have you tried chaning the Content-Type header?

**Comment by samvv** [comment]
I will try it, thanks.

**Comment by samvv** [comment]
Small update: I've made the change to the source code, but I've yet to test it out. I'll keep you posted.

**Comment by samvv** [comment]
Nope it keeps failing. Tried both `text/plain` and `application/octet-stream`.

**Comment by sreeise** [comment]
> Nope it keeps failing. Tried both `text/plain` and `application/octet-stream`.

Ok, thanks for reporting. I'll keep this open as a bug.

**Comment by billykater** [comment]
Came across the same issue today.

Investigating this I found that the most likely culprit is how the file is read (still new to rust)

Internally all BodyRead impls seem to read the whole file content into a string. As strings in rust are only allowed to contain UTF-8 content this will fail horribly if you try to upload a binary file. Changing the content of my file to a UTF-8 string allowed me to get a response from the server instead of a preflight error.

**Comment by samvv** [comment]
Oh thanks for investigating this! I'm wondering if the binary data is then still valid? Uploading binary as UTF-8, even with the right header, does not seem valid.

**Comment by billykater** [comment]
Sorry for being unclear in my response: I just tried to upload a file containing a test string "test" instead of my actual content to validate my suspicion. Of course you simply can't convert any random [u8] to a valid string (hence the error we are both experiencing). 

I am still digging to see if there is an option to bypass the BodyRead struct to upload binary files.

**Comment by sreeise** [comment]
@samvv @buhaytza2005 @billykater Thanks yall for continuing to look into this.

For context, the upload sessions using multipart upload have to know the size of the content before hand because each request must specify what range of bytes is being sent out of the total size of the content which is why all of the data is read in.

Just off the top of my head I do wonder how would binary files be uploaded via an http api if they cannot be converted to valid UTF-8 because that is actually required for http requests. But there probably is some solution to this i'm just not aware of.

**Comment by sreeise** [comment]
> Came across the same issue today.
> 
> Investigating this I found that the most likely culprit is how the file is read (still new to rust)
> 
> Internally all BodyRead impls seem to read the whole file content into a string. As strings in rust are only allowed to contain UTF-8 content this will fail horribly if you try to upload a binary file. Changing the content of my file to a UTF-8 string allowed me to get a response from the server instead of a preflight error.

I should have looked closer at this. You are right. https://github.com/sreeise/graph-rs-sdk/blob/7aa756af45fafec43156d798fff1c47c3fb04b9b/graph-http/src/core/body_read.rs#L30-L34

The impl needs to change to handle this properly.

**Comment by sreeise** [comment]
PR in progress. Still need to do some testing. The PR changes what readers and other byte types are converted to and removes the string conversion of course. Each of these types will be read into a `Vec<u8>` and then passed to the `reqwest::Body` or `reqwest::blocking::Body`.

**Comment by sreeise** [comment]
Thank you @billykater, @samvv, and @buhaytza2005 for continuing to report on this issue and for finding out what was causing it.

I have merged a fix for this issue and added examples as well as updated the README.

**Comment by sreeise** [comment]
Updated in crate version 2.0.1 https://crates.io/crates/graph-rs-sdk/2.0.1
