### ISSUE TITLE
Add interactive authentication for public clients

### ISSUE THREAD

**Issue by kulst** [sreeise/graph-rs-sdk#490]
Microsoft supports interactive authentication for public clients in their authentication libraries MSAL. 
See for example their [Python library](https://learn.microsoft.com/de-de/entra/msal/python/getting-started/acquiring-tokens#acquire-token-interactive)

As far as I can see **graph-oauth** currently does only support _Device code flow_ and _username and password authentication_ for public clients.
_Interactive authentication_ is only supported for confidential clients.

I suggest to also add _Interactive authentication_ for public clients.

**Comment by sreeise** [comment]
> Microsoft supports interactive authentication for public clients in their authentication libraries MSAL. See for example their [Python library](https://learn.microsoft.com/de-de/entra/msal/python/getting-started/acquiring-tokens#acquire-token-interactive)
> 
> As far as I can see **graph-oauth** currently does only support _Device code flow_ and _username and password authentication_ for public clients. _Interactive authentication_ is only supported for confidential clients.
> 
> I suggest to also add _Interactive authentication_ for public clients.

Interactive auth is supported for public clients. For device code a public client is the only option because its not considered a confidential flow. Example here: https://github.com/sreeise/graph-rs-sdk/blob/master/examples/interactive_auth/device_code.rs

Internal method that returns the public client: https://github.com/sreeise/graph-rs-sdk/blob/804467c7d34f38c850e6174ee3d5d3485ddebdaa/graph-oauth/src/identity/credentials/device_code_credential.rs#L632

For username/password auth, yeah your right on that one. I don't believe its been added.
